# Generated by Django 4.2.6 on 2023-11-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_city_owner_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='owner',
        ),
    ]
